- name: "ping the server"
  hosts: frontend
  tasks: 
   - name: "ping"
     ansible.builtin.ping:

#ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 01-playbook.yaml