- name: variables from files
  hosts: local
  vars_files:
  - details.yaml
  tasks:
    - name: print the details
      ansible.builtin.debug:
        msg: "This is {{ Name }}, from {{ Country }} data source {{ Source_from }}."