- name: functions
  hosts: local
  connection: local
  vars:
    technologies: Shell, Ansible, Git, Terraform
  tasks:
  - name: default variables
    ansible.builtin.debug:
      msg: "Hello, {{ name | default('Rahul')}}" #It will print the Rahul using default variable if the name variable is not mentioned

  - name: convert string to list
    ansible.builtin.split: 
     output: "{{ technologies | split(',') }}"
      
    
      

