- name: functions
  hosts: local
  connection: local
  vars:
    technologies: Shell, Ansible, Git, Terraform
    user_details:
      Azhar: Hyderabad
      Rahul: Chennai
      Vijay: Delhi
  tasks:
  - name: default variables
    ansible.builtin.debug:
      msg: "Hello, {{ name | default('Rahul')}}" #It will print the Rahul using default variable if the name variable is not mentioned

  - name: convert string to list
    ansible.builtin.debug: 
     msg: "{{ technologies | split(',')}}"
  
  - name: dictionary into a list
    ansible.builtin.debug:
      msg: "{{ user_details | dict2items }}"
    
      

